<template>
  <section class="section">
    <h1>{{componentName}}</h1>
    <p>
      Hey I'm your new slice 🍕I've been generated by SliceMachine.
      <br/>
      Feel free to make me yours by updating my code ✌️
    </p>
    <p>
      Or pass me props at <a target="_blank" :href="endpoint">{{ endpoint }}</a>
    </p>
  </section>
</template>
<script>
export default {
  props: ['slice'],
  computed: {
    endpoint() {
      return this.$prismic.apiEndpoint.split('/').slice(0, -2).join('/')
    }
  }
}
</script>
<style scoped>
.section {
  position: relative;
  background: #FFFF63;
  color: #111;
  padding: 4em;
  text-align: center;
}
</style>

