<template>
  <section class="section">
    <prismic-rich-text v-if="{{field}}" :field="{{field}}" />
    <p>
      Hey I'm your new slice 🍕I've been generated by SliceMachine.
      <br/>
      Feel free to make me yours by updating my code ✌️
    </p>
    <p v-if="endpoint">
      Or pass me props at <a target="_blank" :href="endpoint">{{ endpoint }}</a>
    </p>
  </section>
</template>
<script>
export default {
  props: ['slice'],
  computed: {
    endpoint() {
      return this.$prismic && this.$prismic.apiEndpoint
        ? this.$prismic.apiEndpoint.split('/').slice(0, -2).join('/').replace('cdn.', '')
        : null
    }
  }
}
</script>
<style scoped>
.section {
  position: relative;
  background: {{colorCode}};
  color: #111;
  padding: 4em;
  text-align: center;
}
</style>

